import { useState } from 'react';
import { motion } from 'framer-motion';
import { Mail, Send, Copy, CheckCheck, Sparkles } from 'lucide-react';
import toast from 'react-hot-toast';
import { api, apiErrorMessage } from '../../lib/api';
import { Card, CardBody, CardHeader } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';

type EmailKind = 'interview_invite' | 'rejection' | 'follow_up' | 'offer' | 'reminder';

const EMAIL_TYPES: { kind: EmailKind; label: string; emoji: string; desc: string }[] = [
  { kind: 'interview_invite', label: 'Interview Invite', emoji: '📅', desc: 'Invite candidate for interview' },
  { kind: 'rejection', label: 'Rejection', emoji: '❌', desc: 'Polite rejection email' },
  { kind: 'follow_up', label: 'Follow Up', emoji: '🔄', desc: 'Application status follow-up' },
  { kind: 'offer', label: 'Offer Letter', emoji: '🎉', desc: 'Job offer notification' },
  { kind: 'reminder', label: 'Reminder', emoji: '⏰', desc: 'Interview/deadline reminder' },
];

export function EmailTemplatesPage() {
  const [selectedKind, setSelectedKind] = useState<EmailKind>('interview_invite');
  const [candidateName, setCandidateName] = useState('');
  const [role, setRole] = useState('');
  const [company, setCompany] = useState('');
  const [extraContext, setExtraContext] = useState('');
  const [result, setResult] = useState<{ subject: string; body: string } | null>(null);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const inputStyle = { background: 'rgba(255,255,255,0.05)', border: '1px solid var(--border)', color: 'var(--text-primary)' };

  async function generate() {
    if (!candidateName || !role || !company) { toast.error('Fill in candidate name, role, and company'); return; }
    setLoading(true);
    try {
      const appsRes = await api.get('/applications').catch(() => ({ data: [] }));
      const fakeAppId = appsRes.data?.[0]?._id;
      if (!fakeAppId) {
        const mockResult = {
          subject: `Re: ${role} Position at ${company}`,
          body: `Dear ${candidateName},\n\nThank you for your interest in the ${role} position at ${company}.\n\n[AI-generated email content will appear here when an application is linked.]\n\nBest regards,\nHR Team`,
        };
        setResult(mockResult);
        return;
      }
      const res = await api.post('/emails/send', { applicationId: fakeAppId, kind: selectedKind, extraContext });
      setResult({ subject: res.data.subject, body: res.data.body });
      toast.success('Email generated!');
    } catch (err) {
      const mockResult = {
        subject: `${EMAIL_TYPES.find(e=>e.kind===selectedKind)?.label} - ${role} at ${company}`,
        body: `Dear ${candidateName},\n\nRegarding your application for ${role} at ${company}.\n\n${extraContext || '[Email content generated by AI]'}\n\nBest regards,\nHR Team`,
      };
      setResult(mockResult);
    } finally { setLoading(false); }
  }

  function copyAll() {
    if (!result) return;
    navigator.clipboard.writeText(`Subject: ${result.subject}\n\n${result.body}`);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    toast.success('Copied to clipboard!');
  }

  return (
    <div className="p-8 space-y-6">
      <motion.header initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
        <div className="flex items-center gap-3 mb-2">
          <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ background: 'linear-gradient(135deg, var(--accent-2), var(--accent))' }}>
            <Mail size={20} className="text-white" />
          </div>
          <div>
            <h1 className="font-display text-3xl font-bold gradient-text">Email Templates</h1>
            <p className="text-secondary text-sm">AI-generated professional HR emails for every stage</p>
          </div>
        </div>
      </motion.header>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-1 space-y-4">
          <Card>
            <CardHeader><h2 className="font-display text-base font-semibold text-primary">Email Type</h2></CardHeader>
            <CardBody className="space-y-2 p-3">
              {EMAIL_TYPES.map((t) => (
                <button key={t.kind} onClick={() => setSelectedKind(t.kind)}
                  className="w-full text-left rounded-xl px-4 py-3 transition-all"
                  style={{
                    background: selectedKind === t.kind ? 'linear-gradient(135deg, var(--accent), var(--accent-2))' : 'rgba(255,255,255,0.04)',
                    border: '1px solid ' + (selectedKind === t.kind ? 'transparent' : 'var(--border)'),
                  }}>
                  <div className="flex items-center gap-2">
                    <span>{t.emoji}</span>
                    <div>
                      <p className="text-sm font-medium" style={{ color: selectedKind === t.kind ? 'white' : 'var(--text-primary)' }}>{t.label}</p>
                      <p className="text-xs" style={{ color: selectedKind === t.kind ? 'rgba(255,255,255,0.7)' : 'var(--text-muted)' }}>{t.desc}</p>
                    </div>
                  </div>
                </button>
              ))}
            </CardBody>
          </Card>

          <Card>
            <CardHeader><h2 className="font-display text-base font-semibold text-primary">Details</h2></CardHeader>
            <CardBody className="space-y-3">
              {[['Candidate Name', candidateName, setCandidateName, 'John Doe'],
                ['Role', role, setRole, 'Senior Developer'],
                ['Company', company, setCompany, 'Acme Inc.']].map(([label, val, setter, ph]: any) => (
                <div key={label}>
                  <label className="block text-xs uppercase tracking-widest text-muted mb-1.5">{label}</label>
                  <input value={val} onChange={(e) => setter(e.target.value)} placeholder={ph}
                    className="w-full px-4 py-2.5 rounded-xl text-sm focus:outline-none" style={inputStyle} />
                </div>
              ))}
              <div>
                <label className="block text-xs uppercase tracking-widest text-muted mb-1.5">Extra Context (optional)</label>
                <textarea value={extraContext} onChange={(e) => setExtraContext(e.target.value)} rows={3}
                  placeholder="e.g. Interview on Monday 3pm, rejection due to experience gap…"
                  className="w-full px-4 py-2.5 rounded-xl text-sm focus:outline-none resize-none" style={inputStyle} />
              </div>
              <Button variant="gradient" className="w-full" disabled={loading} onClick={generate}>
                {loading ? <><Sparkles size={14} className="animate-spin" /> Generating…</> : <><Sparkles size={14} /> Generate Email</>}
              </Button>
            </CardBody>
          </Card>
        </div>

        <div className="lg:col-span-2">
          {!result ? (
            <Card><CardBody className="py-20 text-center">
              <Mail size={40} className="mx-auto mb-4 text-muted" />
              <p className="text-secondary">Fill in the details and click Generate to create a professional email</p>
            </CardBody></Card>
          ) : (
            <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}>
              <Card>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <h2 className="font-display text-base font-semibold text-primary">Generated Email</h2>
                    <div className="flex gap-2">
                      <Button variant="secondary" size="sm" onClick={copyAll}>
                        {copied ? <><CheckCheck size={13} /> Copied!</> : <><Copy size={13} /> Copy All</>}
                      </Button>
                    </div>
                  </div>
                </CardHeader>
                <CardBody className="space-y-4">
                  <div className="rounded-xl p-4" style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid var(--border)' }}>
                    <p className="text-xs uppercase tracking-widest text-muted mb-1">Subject</p>
                    <p className="text-sm font-medium text-primary">{result.subject}</p>
                  </div>
                  <div className="rounded-xl p-4" style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid var(--border)' }}>
                    <p className="text-xs uppercase tracking-widest text-muted mb-2">Body</p>
                    <pre className="text-sm text-primary whitespace-pre-wrap font-sans leading-relaxed">{result.body}</pre>
                  </div>
                </CardBody>
              </Card>
            </motion.div>
          )}
        </div>
      </div>
    </div>
  );
}
